# Generated by Django 6.1.2 on 2026-10-06 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chofer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "cedula",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Cédula de identidad"
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=30)),
                (
                    "licencia",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número de licencia"
                    ),
                ),
                ("vencimiento_licencia", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Choferes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Camion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Matrícula/Chapa"
                    ),
                ),
                ("marca", models.CharField(blank=True, max_length=50)),
                ("modelo", models.CharField(blank=True, max_length=50)),
                (
                    "anio",
                    models.IntegerField(blank=True, null=True, verbose_name="Año"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("en_ruta", "En Ruta"),
                            ("mantenimiento", "En Mantenimiento"),
                            ("inactivo", "Inactivo"),
                        ],
                        default="disponible",
                        max_length=15,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "chofer_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="camion_asignado",
                        to="flota.chofer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Camiones",
                "ordering": ["matricula"],
            },
        ),
    ]
