# Generated by Django 6.1.2 on 2026-10-06 15:13

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flota", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Importador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("ruc", models.CharField(blank=True, max_length=20)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Importadores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Contenedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Ej: MSCU1234567", max_length=20, unique=True
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("20DV", "20' Dry Van"),
                            ("40DV", "40' Dry Van"),
                            ("40HC", "40' High Cube"),
                            ("20RF", "20' Reefer"),
                            ("40RF", "40' Reefer"),
                            ("20OT", "20' Open Top"),
                            ("40OT", "40' Open Top"),
                        ],
                        default="40HC",
                        max_length=5,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_transito", "En Tránsito"),
                            ("aduana_uy", "Aduana UY"),
                            ("aduana_py", "Aduana PY"),
                            ("terminal", "En Terminal"),
                            ("liberado", "Liberado"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="en_transito",
                        max_length=20,
                    ),
                ),
                (
                    "bl_numero",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número BL"
                    ),
                ),
                ("booking", models.CharField(blank=True, max_length=50)),
                ("naviera", models.CharField(blank=True, max_length=100)),
                (
                    "navio",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nave/Buque"
                    ),
                ),
                ("puerto_origen", models.CharField(blank=True, max_length=100)),
                (
                    "puerto_destino",
                    models.CharField(default="Puerto de Asunción", max_length=100),
                ),
                (
                    "eta",
                    models.DateField(
                        blank=True, null=True, verbose_name="ETA (estimada)"
                    ),
                ),
                (
                    "fecha_llegada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha real de llegada"
                    ),
                ),
                (
                    "ultimo_dia_libre",
                    models.DateField(
                        blank=True, null=True, verbose_name="Último día libre"
                    ),
                ),
                (
                    "fecha_liberacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de liberación"
                    ),
                ),
                (
                    "fecha_entrega",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de entrega"
                    ),
                ),
                ("descripcion_carga", models.TextField(blank=True)),
                (
                    "ncm",
                    models.CharField(
                        blank=True,
                        help_text="Nomenclatura Común del MERCOSUR",
                        max_length=20,
                        verbose_name="Código NCM",
                    ),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Peso bruto (kg)",
                    ),
                ),
                (
                    "valor_cif_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor CIF (USD)",
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "camion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contenedores",
                        to="flota.camion",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contenedores_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contenedores_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "importador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contenedores",
                        to="contenedores.importador",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contenedores",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("bl", "Bill of Lading (BL)"),
                            ("factura", "Factura Comercial"),
                            ("packing", "Packing List"),
                            ("dad", "Declaración Aduanera (DAD)"),
                            ("certificado_origen", "Certificado de Origen"),
                            ("seguro", "Póliza de Seguro"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("archivo", models.FileField(upload_to="documentos/")),
                ("subido_en", models.DateTimeField(auto_now_add=True)),
                ("notas", models.CharField(blank=True, max_length=300)),
                (
                    "contenedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="contenedores.contenedor",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Documentos",
                "ordering": ["-subido_en"],
            },
        ),
        migrations.CreateModel(
            name="EventoTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("estado", "Cambio de estado"),
                            ("tracking", "Actualización de tracking"),
                            ("permiso", "Permiso"),
                            ("gasto", "Gasto registrado"),
                            ("documento", "Documento agregado"),
                            ("nota", "Nota"),
                            ("alerta", "Alerta"),
                        ],
                        max_length=15,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "automatico",
                    models.BooleanField(
                        default=False, help_text="Generado por el sistema"
                    ),
                ),
                (
                    "contenedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="contenedores.contenedor",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Eventos de Timeline",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("flete", "Flete internacional"),
                            ("thc", "THC (Terminal Handling)"),
                            ("almacenaje", "Almacenaje"),
                            ("aduana", "Despacho aduanero"),
                            ("arancel", "Arancel MERCOSUR"),
                            ("iva", "IVA importación"),
                            ("tasa_aduana", "Tasa aduanera"),
                            ("transporte", "Transporte interno"),
                            ("despachante", "Honorarios despachante"),
                            ("seguro", "Seguro"),
                            ("permiso", "Permiso regulatorio"),
                            ("demurrage", "Demurrage"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "moneda",
                    models.CharField(
                        choices=[("USD", "USD"), ("PGS", "Guaraníes")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("presupuestado", "Presupuestado"), ("real", "Real")],
                        default="real",
                        max_length=15,
                    ),
                ),
                ("fecha", models.DateField(default=datetime.date.today)),
                (
                    "comprobante",
                    models.FileField(blank=True, null=True, upload_to="comprobantes/"),
                ),
                ("notas", models.CharField(blank=True, max_length=300)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "contenedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gastos",
                        to="contenedores.contenedor",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Gastos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Permiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organismo",
                    models.CharField(
                        choices=[
                            ("SENAVE", "SENAVE (Servicio Nacional de Calidad Vegetal)"),
                            (
                                "INAN",
                                "INAN (Instituto Nacional de Alimentación y Nutrición)",
                            ),
                            (
                                "DINAVISA",
                                "DINAVISA (Dirección de Vigilancia Sanitaria)",
                            ),
                            (
                                "SENACSA",
                                "SENACSA (Servicio Nacional de Calidad y Salud Animal)",
                            ),
                            ("DNA", "DNA (Dirección Nacional de Aduanas)"),
                            ("MADES", "MADES (Ministerio Ambiente)"),
                            ("OTRO", "Otro organismo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("numero_expediente", models.CharField(blank=True, max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_tramite", "En Trámite"),
                            ("aprobado", "Aprobado"),
                            ("observado", "Observado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                ("fecha_solicitud", models.DateField(blank=True, null=True)),
                ("fecha_aprobacion", models.DateField(blank=True, null=True)),
                (
                    "plazo_dias",
                    models.IntegerField(
                        blank=True,
                        help_text="Plazo estimado en días hábiles",
                        null=True,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "documento",
                    models.FileField(blank=True, null=True, upload_to="permisos/"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "contenedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permisos",
                        to="contenedores.contenedor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Permisos",
                "ordering": ["organismo"],
            },
        ),
    ]
