# Generated by Django 6.1.2 on 2026-10-06 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrackingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenedor_numero", models.CharField(db_index=True, max_length=20)),
                (
                    "fuente",
                    models.CharField(
                        choices=[("shipsgo", "ShipsGo"), ("terminal49", "Terminal49")],
                        max_length=15,
                    ),
                ),
                ("datos_raw", models.JSONField()),
                (
                    "consultado_en",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("exitoso", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Tracking Snapshots",
                "ordering": ["-consultado_en"],
            },
        ),
    ]
